# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e96495e3193ad476b26d52c5fdac3dfb1e253487ba4b853ec640d5fc7090236b59469714639c5a7682b44242308991129e0d0ea8edc468f56b7d7af255068f

test:
  secret_key_base: 9cee61b36623c75d796d2cf0b8b0aa6b8498f6671f831f38b6309e35cb4d59f48ed438a003ad25de302e1e68d107231f111aa14dadcad5e6b895a0f61a0535f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
